name: composite actions test

on:
  push:

jobs:
  composite-action:
    name: job to test a composite action

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Composite Action
        id: compositeAction

        uses: ./

        with:
          number1: 4
          number2: 2

      - name: Show Result

        run: |
          echo ${{ steps.compositeAction.outputs.result }}
